import { Outfit, Ovo } from "next/font/google"
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"], weights: ["400", "500", "600", "700"]
});

const ovo = Ovo({
  subsets: ["latin"], weight: ["400"]
});

export const metadata = {
  title: "Rasyadwa Arsya's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`${outfit.className} ${ovo.className} antialiased leading-8
          overflow-x-hidden dark:bg-(--color-dark-theme)
          dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
